#
# From https://medium.com/mistergreen-engineering/uploading-a-docker-image-to-gcr-using-github-actions-92e1cdf14811
#

name: Build
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    env:
      SERVICE_NAME: gamefi-bsc-portal
      HASH: $(git rev-parse --short "$GITHUB_SHA")
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker -q

      # Build docker image
      - name: Image
        run: |-
          docker build -t eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA -t eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:latest .

      # Push image to Google Container Registry
      - name: Push
        run: |-
          docker push eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
          docker push eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:latest

      - name: Deploy
        run: |-
          gcloud compute ssh ${{ secrets.GCP_USER }}@${{ secrets.GCP_INSTANCE }} --zone=${{ secrets.GCP_ZONE }} --command="id"
          gcloud compute ssh ${{ secrets.GCP_USER }}@${{ secrets.GCP_INSTANCE }} --zone=${{ secrets.GCP_ZONE }} --command="docker ps"
          gcloud compute ssh ${{ secrets.GCP_USER }}@${{ secrets.GCP_INSTANCE }} --zone=${{ secrets.GCP_ZONE }} --command="docker-compose -f docker-compose.gcp.yml down"
          gcloud compute ssh ${{ secrets.GCP_USER }}@${{ secrets.GCP_INSTANCE }} --zone=${{ secrets.GCP_ZONE }} --command="docker-compose -f docker system prune -a -f"
          gcloud compute ssh ${{ secrets.GCP_USER }}@${{ secrets.GCP_INSTANCE }} --zone=${{ secrets.GCP_ZONE }} --command="docker-compose -f docker-compose.gcp.yml up -force-recreate -d"
          gcloud compute ssh ${{ secrets.GCP_USER }}@${{ secrets.GCP_INSTANCE }} --zone=${{ secrets.GCP_ZONE }} --command="docker ps"

